### ISSUE TITLE
[BUG] Data such as AC is not displayed and an error occurs when clicking“Edit Stats” in the settings

### ISSUE THREAD

**Issue by kagangtuya-star** [ironmonk88/monks-tokenbar#394]
**Describe the bug**
Data such as AC is not displayed，and an error occurs when clicking“Edit Stats” in the settings

**To Reproduce**
1. Data such as AC is not displayed
2. Click on “Edit Stats” in the settings
3. See error

**Expected behavior**
please fix it...This seems to only happen with v11, and my friend doesn't have this problem with V10

**Screenshots**
![image](https://github.com/ironmonk88/monks-tokenbar/assets/73411104/ee9fbeff-9297-4a61-9a5f-7d00c06d4bb4)
![image](https://github.com/ironmonk88/monks-tokenbar/assets/73411104/e4ff6d31-0b5d-4cdf-94a6-12a099e5980c)

**Please complete as much of the following information as possible:**
 - Browser [edge]
 - Foundry Version [v11.306]
 - System [D&D5e 2.2.2]
 - Module version [11.01]
 - Are there any errors in the console 
```javascript
editstats.js:10  Uncaught TypeError: stats.map is not a function
    at new EditStats (editstats.js:10:28)
    at SettingsConfig._onClickSubmenu (foundry.js:82272:17)
    at HTMLButtonElement.dispatch (jquery.min.js:2:43184)
    at y.handle (jquery.min.js:2:41168)
```
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction.
   I turned off all the mods, only turned on this one but still no improvement.

**Additional context**
Thanks for this very useful work!

**Comment by ironmonk88** [comment]
Not sure how that happened.  Somehow the stats got set to blank.
Should be fixed in the latest version, but you could also fix it by resetting the settings.

**Comment by kagangtuya-star** [comment]
I seem to have found the cause of the problem. 
An unknown conflict mod sets the stats to blank and can not be recovered. And can not be undone by resetting settings.
```
Uncaught TypeError: (stats || []).map is not a function
at new EditStats (editstats.js:10:36)
at ExtendedSettingsConfig._onClickSubmenu (foundry.js:82272:17)
at HTMLButtonElement.dispatch (jquery.min.js:2:43184)
at y.handle (jquery.min.js:2:41168) 
```

Using the latest version still encountered errors, I tried to modify the code with my own understanding, and maybe resolved.
The original code is
```
// https://github.com/ironmonk88/monks-tokenbar/blob/ad5ce359ab489f46adb9596d7ff667c8b56d187f/apps/editstats.js#L10C1-L10C1
this.stats = (stats || []).map(s => {
s.id = s.id || makeid();
return s;
}); 
```
The broken stats may not be an array, so an error occurred.
So I changed the code to
```
        if (!Array.isArray(stats)) {
            stats = []; 
        }
       // If the stats is not an array, construct an empty array instead.
        this.stats = stats.map(s => {
            s.id = s.id || makeid();
            return s;
        });
```
Thus, I solved the problem, and although I needed to manually add the stats that were purged due to corruption.
![image](https://github.com/ironmonk88/monks-tokenbar/assets/73411104/e60bbac6-61a3-4f08-aab8-81ce6b8ade75)
For me, it works fine now.

**Comment by kagangtuya-star** [comment]
And I created a pull requests
https://github.com/ironmonk88/monks-tokenbar/pull/396
