### ISSUE TITLE
Dice so Nice + Monk's Token Bar - Public Rolls not working in 12.02 (fine in 12.01)

### ISSUE THREAD

**Issue by matt-duffy** [ironmonk88/monks-tokenbar#519]
**Describe the bug**
If I request a roll using dice so nice and monk's token bar 12.02 as a public roll, the 3d dice are never rolled and the result is not shown unless I (GM) click on the elipsis.

I have tested this with only dice so nice 5.0.5 and Monk's TokenBar 12.02 running and always get the same result.  If I downgrade to 12.01 then it all works as expected, the 3 dice is rolled and the result is displayed.

**To Reproduce**
1. Request a roll with Roll Mode "Public Roll", click the Request button
2. User rolls from the chat card

**Expected behavior**
1. 3d dice are rolled
2. The result is automatically shown

**Screenshots**
GM Requests Roll:

https://github.com/user-attachments/assets/54bd21bd-9c12-41b2-b38a-b5bcc151e8f9

Player Rolls (no dice roll):

https://github.com/user-attachments/assets/9bdb6b35-4c77-4d3e-a45e-d1cc94d61f54

GM has to click to show it:

https://github.com/user-attachments/assets/cb4cecbd-75ce-45fb-9cdd-66125a3bdd16

**Please complete as much of the following information as possible:**
 - Browser: Tested in Edge and Firefox
 - Foundry Version 12.331
 - System D&D 5e 3.3.1
 - Module version 12.02
 - Are there any errors in the console [e.g. press F12 and look for red text] - Not on GM or player side
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction. - As above have tested with only dice so nice and Monk's TokenBar running

**Additional context**
I did note that it looked like this issue had a fix in the last release, perhaps this caused it?

https://github.com/ironmonk88/monks-tokenbar/issues/494

**Comment by Vagabondluc** [comment]
I have this issue since im in v12 (end of june).

I thought at first it was midi-qol. But after playing some sessions without midi-qol, monk token bar was my second guess. 

I dont know if it related to this issue, but rolls dont even seem to work after a while.

It super hard to diagnose because the issue is intermittent.

Anyways, monk token bar is disabled in my world right now and i dont have thoses issues anymore.

But i really miss monk token bar.

**Comment by ironmonk88** [comment]
Fixed in the latest version

**Comment by Vagabondluc** [comment]
![image](https://github.com/user-attachments/assets/daf3e545-fce0-4949-a0c3-5b222e469ed9)
![image](https://github.com/user-attachments/assets/7ad025dd-33c6-48c2-854f-de42ac89ee0f)

![image](https://github.com/user-attachments/assets/f15d7b2e-7248-4357-8814-dfdc15128408)

I think i'm on the last version and i still have problems.

**Comment by matt-duffy** [comment]
This seems to be fixed for me now, but now I have another issue that I will raise

**Comment by matt-duffy** [comment]
Scrap that, my mistake, it is working fine for me, would be handy if you could set the minimum system version in the module though as my real server is still stuck on v3 D&D until a last couple of modules update and the latest version doesn't work in D&D v3.

Thanks for the great module!  Dice so Nice and Monk's Token bar are my 2 most used far and away.
